name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          apt update -y && apt upgrade -y
          apt install -y clang-13 lld-13 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          PATH="$HOME/.cargo/bin:$PATH"

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          make build
          make run

      - name: objdump
        run: |
          make objdump
