name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          bash ci/deb_install.sh

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          make build
          make run

      - name: objdump
        run: |
          make objdump

      - name: cxx
        run: |
          make cxx_configure
          make cxx_build
          make cxx_run
          make cxx_bench
